/*
 Este formulario, tendra dos opciones dependiendo del usuario
 * Si el usuario es el gerente, se mostrara el boton "Nuevo mensaje" y "Borrar"
 * Si es agente o auditor se esconderan dichos botones.
 * Se envia al constructor el tipo de usuario, para saber diferenciar entre usuarios y gerente.
 * Se envia al constructor el nombre del usuario para mostrarlo en el formulario
 * Se necesita un campo FECHA en la tabla MENSAJE para poder ordenar los mensajes cronologicamente.
 */
package pantallas.mensajeria;

import clases.Mensaje;
import clases.Sistema;
import clases.Usuario;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.*;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ed
 */
public final class Bandeja extends javax.swing.JFrame {

    String query, delType, user;
    Statement declaracion;
    ResultSet rs;
    Usuario u;
    boolean esGerente = false;
    String tipoBand;
    Mensaje gm;

    /*Se crea una instancia de este objeto para utilizar sus metodos como conexion 
     a la Base de datos, actulizacione etc. */
    Calendar c = Calendar.getInstance();

    /**
     *
     * @param u
     * @param tipo
     */
    public Bandeja(Usuario u, String tipo) {//aqui va a recibir un objeto usuario
        this.u = new Usuario();
        this.u.setNombreUsuario(u.getNombreUsuario());
        this.u.setUser(u.getUser());
        this.u.setListaTiposUsuario(u.getListaTiposUsuario());
        user = this.u.getUser();
        tipoBand = tipo;
        gm = new Mensaje(u, tipoBand);
        if (u.getListaTiposUsuario().size() == 1) {
            esGerente = this.u.getListaTiposUsuario().get(0).getCodigoTipoUser() == 3;
        } else {
            esGerente = this.u.getListaTiposUsuario().get(0).getCodigoTipoUser() == 3 || this.u.getListaTiposUsuario().get(1).getCodigoTipoUser() == 3;
        }
        initComponents();
        ed_textarea1.setLineWrap(true);
        ed_textarea1.setWrapStyleWord(true);
        setSize(1024, 680);
        setLocationRelativeTo(null);

        if (esGerente) {
            refrescarTabla(ed_table_in_out_box);
            this.ed_label_title.setText("Mensajeria - Bandeja de Salida");
        } else {

            refrescarTabla(ed_table_in_out_box);
            this.ed_button_new.setVisible(false);
            this.ed_button_del.setVisible(false);
            this.ed_label_title.setText("Mensajeria - Bandeja de Entrada");
        }
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.ed_label_usuario.setText(nombreUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ed_button_del = new javax.swing.JButton();
        ed_button_empty = new javax.swing.JButton();
        ed_button_refresh = new javax.swing.JButton();
        ed_button_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ed_table_in_out_box = new javax.swing.JTable();
        ed_textarea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ed_label_title = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mensajeria - Bandeja - SIAPO");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(94, 112, 144));
        jPanel5.setForeground(new java.awt.Color(94, 112, 144));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universidad de El Salvador ©Copyright 2013 ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ed_button_del.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ed_button_del.setText("Borrar");
        ed_button_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_button_delActionPerformed(evt);
            }
        });

        ed_button_empty.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ed_button_empty.setText("Vaciar Bandeja");
        ed_button_empty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_button_emptyActionPerformed(evt);
            }
        });

        ed_button_refresh.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ed_button_refresh.setText("Actualizar");
        ed_button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_button_refreshActionPerformed(evt);
            }
        });

        ed_button_new.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ed_button_new.setText("Nuevo mensaje");
        ed_button_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_button_newActionPerformed(evt);
            }
        });

        ed_table_in_out_box.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ed_table_in_out_box.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ed_table_in_out_box.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        ed_table_in_out_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ed_table_in_out_boxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ed_table_in_out_box);

        ed_textarea1.setEditable(false);
        ed_textarea1.setColumns(40);
        ed_textarea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ed_textarea1.setLineWrap(true);
        ed_textarea1.setRows(5);
        ed_textarea1.setWrapStyleWord(true);
        ed_textarea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(60, 117, 207));

        jPanel2.setBackground(new java.awt.Color(47, 63, 79));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(Integer.toString(c.get(Calendar.DATE))+"-"+Integer.toString(c.get(Calendar.MONTH)+1)+"-"+Integer.toString(c.get(Calendar.YEAR)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        try{
            jLabel17.setText(this.u.getNombreUsuario()+"-"+this.u.getListaTiposUsuario().get(0).getNombreTipo()+"-"+this.u.getListaTiposUsuario().get(1).getNombreTipo());
        }catch(Exception e){
            jLabel17.setText(this.u.getNombreUsuario()+"-"+this.u.getListaTiposUsuario().get(0).getNombreTipo());
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jPanel3.setBackground(new java.awt.Color(94, 112, 144));
        jPanel3.setForeground(new java.awt.Color(94, 112, 144));

        ed_label_title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ed_label_title.setForeground(new java.awt.Color(255, 255, 255));
        ed_label_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ed_label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ed_label_title, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo HMCR.jpg"))); // NOI18N

        jButton12.setBackground(new java.awt.Color(60, 117, 207));
        jButton12.setForeground(new java.awt.Color(60, 117, 207));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1378460112_home.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Menú principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ed_button_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ed_button_empty, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ed_button_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ed_button_del, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ed_textarea1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(ed_textarea1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ed_button_del)
                    .addComponent(ed_button_empty)
                    .addComponent(ed_button_refresh)
                    .addComponent(ed_button_new))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ed_button_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_button_newActionPerformed
        // TODO add your handling code here:
        pantallas.gerente.sendMessage m = new pantallas.gerente.sendMessage();
        m.setVisible(true);
    }//GEN-LAST:event_ed_button_newActionPerformed

    private void ed_button_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_button_delActionPerformed
        // TODO add your handling code here:
        if (esGerente) {
            delType = "uno";
        } else {
            delType = "ocultaruno";
        }
        eliminarMensajes(ed_table_in_out_box, delType);
        dispose();
    }//GEN-LAST:event_ed_button_delActionPerformed

    private void ed_button_emptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_button_emptyActionPerformed
        // TODO add your handling code here:
        if (esGerente) {
            delType = "todo";
            eliminarMensajes(ed_table_in_out_box, delType);
        } else {
            delType = "ocultartodo";
            eliminarMensajes(ed_table_in_out_box, delType);
        }
        dispose();
    }//GEN-LAST:event_ed_button_emptyActionPerformed

    private void ed_button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_button_refreshActionPerformed
        //Vuelve a recuperar la informacion desde la base de datos hacia la JTable
        refrescarTabla(this.ed_table_in_out_box);
    }//GEN-LAST:event_ed_button_refreshActionPerformed

    private void ed_table_in_out_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ed_table_in_out_boxMouseClicked
        /* La funcion de este evento es el de cargar los mensajes enviados
         por medio de la lectura de datos del JTable y dicha informacion la carga al area de texto.
         */
        if (ed_table_in_out_box.getValueAt(this.ed_table_in_out_box.getSelectedRow(), 0).toString().equals("NUEVO")) {
            ed_table_in_out_box.setValueAt("leido", this.ed_table_in_out_box.getSelectedRow(), 0);
        }
        String aux = ed_table_in_out_box.getValueAt(this.ed_table_in_out_box.getSelectedRow(), 1).toString().trim();
        query = "SELECT asunto,contenido FROM mensaje WHERE idMensaje=" + aux + ";";
        try {
            declaracion = gm.conexion("root");
            rs = declaracion.executeQuery(query);
            rs.next();
            this.ed_textarea1.setText("Asunto:\n" + rs.getString(1) + ".\n\n" + "Mensaje: \n" + rs.getString(2) + ".\n\n (Fin del mensaje.)");
            gm.cerrarConexiones();
            Sistema s = new Sistema();
            if (tipoBand.equals("mensaje")) {
                s.actualizar("gestiona,mensaje", "gestiona.visto=1",
                        "user='" + user + "' AND mensaje.idMensaje=gestiona.idMensaje "
                        + "AND gestiona.idMensaje=" + aux + " AND mensaje.tipoMensaje =1");
            } else {
                s.actualizar("gestiona,mensaje", "gestiona.visto=1",
                        "user='" + user + "' AND mensaje.idMensaje=gestiona.idMensaje "
                        + "AND gestiona.idMensaje=" + aux + " AND mensaje.tipoMensaje =2");
            }
            /*
             UPDATE gestiona,mensaje 
             * SET gestiona.visto =1 
             * WHERE user =  'jfuentes' 
             * AND mensaje.idMensaje = gestiona.idMensaje 
             * AND mensaje.tipoMensaje =1
             */
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_ed_table_in_out_boxMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void eliminarMensajes(JTable tabla, String delType) {
        String aux;
        int confirm; //Aprobacion para eliminar mensaje o mensajes.
        switch (delType) {
            case "todo":
                confirm = JOptionPane.showConfirmDialog(null, "¿Esta seguro de vaciar la bandeja de mensajes?", "Eliminar mensaje.", JOptionPane.WARNING_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    gm.deleteAll();
                    this.ed_textarea1.setText("");
                } else {
                    new Bandeja(u, tipoBand).setVisible(true);
                }
                break;
            case "uno":
                aux = tabla.getValueAt(tabla.getSelectedRow(), 1).toString().trim();
                confirm = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este mensaje?", "Eliminar mensaje.", JOptionPane.WARNING_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    gm.deleteOne(aux);
                    this.ed_textarea1.setText("");
                } else {
                    new Bandeja(u, tipoBand).setVisible(true);
                }
                break;
            case "ocultartodo":
                confirm = JOptionPane.showConfirmDialog(null, "¿Esta seguro de vaciar la bandeja de mensajes?", "Eliminar mensaje.", JOptionPane.WARNING_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    gm.ocultarAll(user);
                    this.ed_textarea1.setText("");
                } else {
                    new Bandeja(u, tipoBand).setVisible(true);
                }
                break;
            case "ocultaruno":
                aux = tabla.getValueAt(tabla.getSelectedRow(), 1).toString().trim();
                confirm = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este mensaje?", "Eliminar mensaje.", JOptionPane.WARNING_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    gm.ocultarOne(aux, user);
                    this.ed_textarea1.setText("");
                } else {
                    new Bandeja(u, tipoBand).setVisible(true);
                }
                break;
            default:
                break;
        }

    }

    /**
     * ***************************************
     * @param tabla
     */
    public void refrescarTabla(JTable tabla) {
        //Esta funcion permite la recuperacion de mensajes desde la base de datos hacia la bandeja de mensajes

        String[] titulos = {"Estado", "Codigo", "Fecha", "Hora", "Asunto"};
        if (tipoBand.equals("mensaje")) {
            if (esGerente) {
                query = "SELECT idMensaje,asunto,date(fechaHoraMensaje) as fecha,time(fechaHoraMensaje) as hora FROM mensaje WHERE "
                        + "mensaje.tipoMensaje=1) ORDER BY fechaHoraMensaje DESC;";
            } else {
                query = "SELECT mensaje.idMensaje,asunto,date(fechaHoraMensaje) as fecha,time(fechaHoraMensaje) as hora,visto FROM mensaje, gestiona WHERE "
                        + "( mensaje.idMensaje = gestiona.idMensaje "
                        + "AND gestiona.user = \"" + user + "\" AND gestiona.oculto = '0'"
                        + " AND mensaje.tipoMensaje=1) ORDER BY fechaHoraMensaje DESC;";
            }
        } else {
            query = "SELECT mensaje.idMensaje,asunto,date(fechaHoraMensaje) as fecha,time(fechaHoraMensaje) as hora,visto FROM mensaje,puede_tener, gestiona WHERE "
                    + "( mensaje.idMensaje = gestiona.idMensaje "
                    + "AND gestiona.user = \"" + user + "\" AND gestiona.oculto = "
                    + "'0' AND mensaje.tipoMensaje=2 AND puede_tener.idMensaje = mensaje.idMensaje AND errorLaboratorio =0) ORDER BY fechaHoraMensaje DESC;";
        }
        declaracion = null;
        rs = null;
        DefaultTableModel model = new DefaultTableModel(null, titulos);

        try {
            declaracion = gm.conexion("root");
            if (esGerente) {
                rs = declaracion.executeQuery("SELECT idMensaje,asunto,date(fechaHoraMensaje) as fecha,time(fechaHoraMensaje) as hora FROM mensaje WHERE tipoMensaje=1 ORDER BY fechaHoraMensaje DESC");
            } else {
                rs = declaracion.executeQuery(query);
            }

            String[] fila = new String[5];
            //rs.beforeFirst();
            while (rs.next()) {
                if (!esGerente) {
                    if (rs.getInt("visto") == 0) {
                        fila[0] = "NUEVO";
                    } else {
                        fila[0] = "leido";
                    }
                } else {
                    fila[0] = "ENVIADO";
                }
                fila[1] = rs.getString("idMensaje");
                fila[2] = rs.getString("fecha");
                fila[3] = rs.getString("hora");
                fila[4] = rs.getString("asunto");
                model.addRow(fila);
                tabla.setModel(model);
            }
            if (tabla.getColumnCount() > 0) {
                tabla.getColumnModel().getColumn(1).setMaxWidth(0);
                tabla.getColumnModel().getColumn(1).setMinWidth(0);
                tabla.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
                tabla.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
            }
            gm.cerrarConexiones();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, null, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, null, JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ed_button_del;
    private javax.swing.JButton ed_button_empty;
    private javax.swing.JButton ed_button_new;
    private javax.swing.JButton ed_button_refresh;
    private javax.swing.JLabel ed_label_title;
    private javax.swing.JTable ed_table_in_out_box;
    private javax.swing.JTextArea ed_textarea1;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
